#pragma once
#include <unordered_map>
#include <string>
#include <bitset>
#include <iostream>
#include <cstdlib>

#ifndef INLINE_FORCE
#define INLINE_FORCE __attribute__((always_inline)) inline
#endif


// Bitmap positions for all lockable items (expandable)
enum ItemID : size_t {
    // Vouchers
    OVERSTOCK_PLUS = 0,
    LIQUIDATION = 1,
    GLOW_UP = 2,
    REROLL_GLUT = 3,
    OMEN_GLOBE = 4,
    OBSERVATORY = 5,
    NACHO_TONG = 6,
    RECYCLOMANCY = 7,
    TAROT_TYCOON = 8,
    PLANET_TYCOON = 9,
    MONEY_TREE = 10,
    ANTIMATTER = 11,
    ILLUSION = 12,
    PETROGLYPH = 13,
    RETCON = 14,
    PALETTE = 15,
    
    // Tags
    NEGATIVE_TAG = 16,
    FOIL_TAG = 17,
    HOLOGRAPHIC_TAG = 18,
    POLYCHROME_TAG = 19,
    RARE_TAG = 20,
    
    // Jokers (commonly locked ones)
    GOLDEN_TICKET = 21,
    MR_BONES = 22,
    ACROBAT = 23,
    SOCK_AND_BUSKIN = 24,
    SWASHBUCKLER = 25,
    TROUBADOUR = 26,
    CERTIFICATE = 27,
    SMEARED_JOKER = 28,
    THROWBACK = 29,
    HANGING_CHAD = 30,
    ROUGH_GEM = 31,
    BLOODSTONE = 32,
    ARROWHEAD = 33,
    ONYX_AGATE = 34,
    GLASS_JOKER = 35,
    SHOWMAN = 36,
    FLOWER_POT = 37,
    BLUEPRINT = 38,
    WEE_JOKER = 39,
    MERRY_ANDY = 40,
    OOPS_ALL_6S = 41,
    THE_IDOL = 42,
    SEEING_DOUBLE = 43,
    MATADOR = 44,
    HIT_THE_ROAD = 45,
    THE_DUO = 46,
    THE_TRIO = 47,
    THE_FAMILY = 48,
    THE_ORDER = 49,
    THE_TRIBE = 50,
    STUNTMAN = 51,
    INVISIBLE_JOKER = 52,
    BRAINSTORM = 53,
    SATELLITE = 54,
    SHOOT_THE_MOON = 55,
    DRIVERS_LICENSE = 56,
    CARTOMANCER = 57,
    ASTRONOMER = 58,
    BURNT_JOKER = 59,
    BOOTSTRAPS = 60,
    
    // All remaining Jokers from items.hpp
    JOKER = 61,
    GREEDY_JOKER = 62,
    LUSTY_JOKER = 63,
    WRATHFUL_JOKER = 64,
    GLUTTONOUS_JOKER = 65,
    JOLLY_JOKER = 66,
    ZANY_JOKER = 67,
    MAD_JOKER = 68,
    CRAZY_JOKER = 69,
    DROLL_JOKER = 70,
    SLY_JOKER = 71,
    WILY_JOKER = 72,
    CLEVER_JOKER = 73,
    DEVIOUS_JOKER = 74,
    CRAFTY_JOKER = 75,
    HALF_JOKER = 76,
    CREDIT_CARD = 77,
    BANNER = 78,
    MYSTIC_SUMMIT = 79,
    EIGHT_BALL = 80,
    MISPRINT = 81,
    RAISED_FIST = 82,
    CHAOS_THE_CLOWN = 83,
    SCARY_FACE = 84,
    ABSTRACT_JOKER = 85,
    DELAYED_GRATIFICATION = 86,
    GROS_MICHEL = 87,
    EVEN_STEVEN = 88,
    ODD_TODD = 89,
    SCHOLAR = 90,
    BUSINESS_CARD = 91,
    SUPERNOVA = 92,
    RIDE_THE_BUS = 93,
    EGG = 94,
    RUNNER = 95,
    ICE_CREAM = 96,
    SPLASH = 97,
    BLUE_JOKER = 98,
    FACELESS_JOKER = 99,
    GREEN_JOKER = 100,
    SUPERPOSITION = 101,
    TO_DO_LIST = 102,
    RED_CARD = 103,
    SQUARE_JOKER = 104,
    RIFF_RAFF = 105,
    PHOTOGRAPH = 106,
    RESERVED_PARKING = 107,
    MAIL_IN_REBATE = 108,
    HALLUCINATION = 109,
    FORTUNE_TELLER = 110,
    JUGGLER = 111,
    DRUNKARD = 112,
    GOLDEN_JOKER = 113,
    POPCORN = 114,
    WALKIE_TALKIE = 115,
    SMILEY_FACE = 116,
    
    // Uncommon jokers continued
    JOKER_STENCIL = 117,
    FOUR_FINGERS = 118,
    MIME = 119,
    CEREMONIAL_DAGGER = 120,
    MARBLE_JOKER = 121,
    LOYALTY_CARD = 122,
    DUSK = 123,
    FIBONACCI = 124,
    HACK = 125,
    PAREIDOLIA = 126,
    SPACE_JOKER = 127,
    BURGLAR = 128,
    BLACKBOARD = 129,
    SIXTH_SENSE = 130,
    CONSTELLATION = 131,
    HIKER = 132,
    CARD_SHARP = 133,
    MADNESS = 134,
    SEANCE = 135,
    VAMPIRE = 136,
    SHORTCUT = 137,
    HOLOGRAM = 138,
    CLOUD_9 = 139,
    ROCKET = 140,
    MIDAS_MASK = 141,
    LUCHADOR = 142,
    GIFT_CARD = 143,
    TURTLE_BEAN = 144,
    EROSION = 145,
    TO_THE_MOON = 146,
    BULL = 147,
    DIET_COLA = 148,
    TRADING_CARD = 149,
    FLASH_CARD = 150,
    SPARE_TROUSERS = 151,
    RAMEN = 152,
    SELTZER = 153,
    CASTLE = 154,
    
    // Rare jokers
    DNA = 155,
    VAGABOND = 156,
    BARON = 157,
    OBELISK = 158,
    BASEBALL_CARD = 159,
    ANCIENT_JOKER = 160,
    CAMPFIRE = 161,
    
    // Legendary jokers
    CANIO = 162,
    TRIBOULET = 163,
    YORICK = 164,
    CHICOT = 165,
    PERKEO = 166,
    
    // Additional items from initLocks (shifted to higher numbers)
    THE_MOUTH = 167,
    THE_FISH = 168,
    THE_WALL = 169,
    THE_HOUSE = 170,
    THE_MARK = 171,
    THE_WHEEL = 172,
    THE_ARM = 173,
    THE_WATER = 174,
    THE_NEEDLE = 175,
    THE_FLINT = 176,
    STANDARD_TAG = 177,
    METEOR_TAG = 178,
    BUFFOON_TAG = 179,
    HANDY_TAG = 180,
    GARBAGE_TAG = 181,
    ETHEREAL_TAG = 182,
    TOP_UP_TAG = 183,
    ORBITAL_TAG = 184,
    THE_TOOTH = 185,
    THE_EYE = 186,
    THE_PLANT = 187,
    THE_SERPENT = 188,
    THE_OX = 189,
    PLANET_X = 190,
    CERES = 191,
    ERIS = 192,
    FIVE_OF_A_KIND = 193,
    FLUSH_HOUSE = 194,
    FLUSH_FIVE = 195,
    STONE_JOKER = 196,
    STEEL_JOKER = 197,
    LUCKY_CAT = 198,
    CAVENDISH = 199,
    
    // Tarot cards that get locked/unlocked during pack generation
    THE_FOOL = 200,
    THE_MAGICIAN = 201,
    THE_HIGH_PRIESTESS = 202,
    THE_EMPRESS = 203,
    THE_EMPEROR = 204,
    THE_HIEROPHANT = 205,
    THE_LOVERS = 206,
    THE_CHARIOT = 207,
    JUSTICE = 208,
    THE_HERMIT = 209,
    THE_WHEEL_OF_FORTUNE = 210,
    STRENGTH_CARD = 211,
    THE_HANGED_MAN = 212,
    DEATH = 213,
    TEMPERANCE = 214,
    THE_DEVIL = 215,
    THE_TOWER = 216,
    THE_STAR_CARD = 217,
    THE_MOON = 218,
    THE_SUN_CARD = 219,
    JUDGEMENT = 220,
    THE_WORLD = 221,
    
    // Planet cards
    MERCURY = 222,
    VENUS = 223,
    EARTH = 224,
    MARS = 225,
    JUPITER = 226,
    SATURN = 227,
    URANUS = 228,
    NEPTUNE = 229,
    PLUTO = 230,
    PLANET_X_CARD = 231,
    CERES_CARD = 232,
    ERIS_CARD = 233,
    
    // Spectral cards
    FAMILIAR = 234,
    GRIM = 235,
    INCANTATION = 236,
    TALISMAN = 237,
    AURA = 238,
    WRAITH = 239,
    SIGIL = 240,
    OUIJA = 241,
    ECTOPLASM = 242,
    IMMOLATE_CARD = 243,
    ANKH = 244,
    DEJA_VU = 245,
    HEX = 246,
    TRANCE = 247,
    MEDIUM = 248,
    CRYPTID = 249,
    
    // Special cards
    THE_SOUL_CARD = 250,
    BLACK_HOLE_CARD = 251
    // Can expand up to 256 or more as needed
};

// Global lookup table for string -> bit position
static const std::unordered_map<std::string, ItemID> ITEM_TO_ID = {
    {"Overstock Plus", OVERSTOCK_PLUS},
    {"Liquidation", LIQUIDATION},
    {"Glow Up", GLOW_UP},
    {"Reroll Glut", REROLL_GLUT},
    {"Omen Globe", OMEN_GLOBE},
    {"Observatory", OBSERVATORY},
    {"Nacho Tong", NACHO_TONG},
    {"Recyclomancy", RECYCLOMANCY},
    {"Tarot Tycoon", TAROT_TYCOON},
    {"Planet Tycoon", PLANET_TYCOON},
    {"Money Tree", MONEY_TREE},
    {"Antimatter", ANTIMATTER},
    {"Illusion", ILLUSION},
    {"Petroglyph", PETROGLYPH},
    {"Retcon", RETCON},
    {"Palette", PALETTE},
    {"Negative Tag", NEGATIVE_TAG},
    {"Foil Tag", FOIL_TAG},
    {"Holographic Tag", HOLOGRAPHIC_TAG},
    {"Polychrome Tag", POLYCHROME_TAG},
    {"Rare Tag", RARE_TAG},
    {"Golden Ticket", GOLDEN_TICKET},
    {"Mr. Bones", MR_BONES},
    {"Acrobat", ACROBAT},
    {"Sock and Buskin", SOCK_AND_BUSKIN},
    {"Swashbuckler", SWASHBUCKLER},
    {"Troubadour", TROUBADOUR},
    {"Certificate", CERTIFICATE},
    {"Smeared Joker", SMEARED_JOKER},
    {"Throwback", THROWBACK},
    {"Hanging Chad", HANGING_CHAD},
    {"Rough Gem", ROUGH_GEM},
    {"Bloodstone", BLOODSTONE},
    {"Arrowhead", ARROWHEAD},
    {"Onyx Agate", ONYX_AGATE},
    {"Glass Joker", GLASS_JOKER},
    {"Showman", SHOWMAN},
    {"Flower Pot", FLOWER_POT},
    {"Blueprint", BLUEPRINT},
    {"Wee Joker", WEE_JOKER},
    {"Merry Andy", MERRY_ANDY},
    {"Oops! All 6s", OOPS_ALL_6S},
    {"The Idol", THE_IDOL},
    {"Seeing Double", SEEING_DOUBLE},
    {"Matador", MATADOR},
    {"Hit the Road", HIT_THE_ROAD},
    {"The Duo", THE_DUO},
    {"The Trio", THE_TRIO},
    {"The Family", THE_FAMILY},
    {"The Order", THE_ORDER},
    {"The Tribe", THE_TRIBE},
    {"Stuntman", STUNTMAN},
    {"Invisible Joker", INVISIBLE_JOKER},
    {"Brainstorm", BRAINSTORM},
    {"Satellite", SATELLITE},
    {"Shoot the Moon", SHOOT_THE_MOON},
    {"Driver's License", DRIVERS_LICENSE},
    {"Cartomancer", CARTOMANCER},
    {"Astronomer", ASTRONOMER},
    {"Burnt Joker", BURNT_JOKER},
    {"Bootstraps", BOOTSTRAPS},
    
    // All remaining Jokers from items.hpp
    {"Joker", JOKER},
    {"Greedy Joker", GREEDY_JOKER},
    {"Lusty Joker", LUSTY_JOKER},
    {"Wrathful Joker", WRATHFUL_JOKER},
    {"Gluttonous Joker", GLUTTONOUS_JOKER},
    {"Jolly Joker", JOLLY_JOKER},
    {"Zany Joker", ZANY_JOKER},
    {"Mad Joker", MAD_JOKER},
    {"Crazy Joker", CRAZY_JOKER},
    {"Droll Joker", DROLL_JOKER},
    {"Sly Joker", SLY_JOKER},
    {"Wily Joker", WILY_JOKER},
    {"Clever Joker", CLEVER_JOKER},
    {"Devious Joker", DEVIOUS_JOKER},
    {"Crafty Joker", CRAFTY_JOKER},
    {"Half Joker", HALF_JOKER},
    {"Credit Card", CREDIT_CARD},
    {"Banner", BANNER},
    {"Mystic Summit", MYSTIC_SUMMIT},
    {"8 Ball", EIGHT_BALL},
    {"Misprint", MISPRINT},
    {"Raised Fist", RAISED_FIST},
    {"Chaos the Clown", CHAOS_THE_CLOWN},
    {"Scary Face", SCARY_FACE},
    {"Abstract Joker", ABSTRACT_JOKER},
    {"Delayed Gratification", DELAYED_GRATIFICATION},
    {"Gros Michel", GROS_MICHEL},
    {"Even Steven", EVEN_STEVEN},
    {"Odd Todd", ODD_TODD},
    {"Scholar", SCHOLAR},
    {"Business Card", BUSINESS_CARD},
    {"Supernova", SUPERNOVA},
    {"Ride the Bus", RIDE_THE_BUS},
    {"Egg", EGG},
    {"Runner", RUNNER},
    {"Ice Cream", ICE_CREAM},
    {"Splash", SPLASH},
    {"Blue Joker", BLUE_JOKER},
    {"Faceless Joker", FACELESS_JOKER},
    {"Green Joker", GREEN_JOKER},
    {"Superposition", SUPERPOSITION},
    {"To Do List", TO_DO_LIST},
    {"Red Card", RED_CARD},
    {"Square Joker", SQUARE_JOKER},
    {"Riff-raff", RIFF_RAFF},
    {"Photograph", PHOTOGRAPH},
    {"Reserved Parking", RESERVED_PARKING},
    {"Mail In Rebate", MAIL_IN_REBATE},
    {"Hallucination", HALLUCINATION},
    {"Fortune Teller", FORTUNE_TELLER},
    {"Juggler", JUGGLER},
    {"Drunkard", DRUNKARD},
    {"Golden Joker", GOLDEN_JOKER},
    {"Popcorn", POPCORN},
    {"Walkie Talkie", WALKIE_TALKIE},
    {"Smiley Face", SMILEY_FACE},
    
    // Uncommon jokers
    {"Joker Stencil", JOKER_STENCIL},
    {"Four Fingers", FOUR_FINGERS},
    {"Mime", MIME},
    {"Ceremonial Dagger", CEREMONIAL_DAGGER},
    {"Marble Joker", MARBLE_JOKER},
    {"Loyalty Card", LOYALTY_CARD},
    {"Dusk", DUSK},
    {"Fibonacci", FIBONACCI},
    {"Hack", HACK},
    {"Pareidolia", PAREIDOLIA},
    {"Space Joker", SPACE_JOKER},
    {"Burglar", BURGLAR},
    {"Blackboard", BLACKBOARD},
    {"Sixth Sense", SIXTH_SENSE},
    {"Constellation", CONSTELLATION},
    {"Hiker", HIKER},
    {"Card Sharp", CARD_SHARP},
    {"Madness", MADNESS},
    {"Seance", SEANCE},
    {"Vampire", VAMPIRE},
    {"Shortcut", SHORTCUT},
    {"Hologram", HOLOGRAM},
    {"Cloud 9", CLOUD_9},
    {"Rocket", ROCKET},
    {"Midas Mask", MIDAS_MASK},
    {"Luchador", LUCHADOR},
    {"Gift Card", GIFT_CARD},
    {"Turtle Bean", TURTLE_BEAN},
    {"Erosion", EROSION},
    {"To the Moon", TO_THE_MOON},
    {"Bull", BULL},
    {"Diet Cola", DIET_COLA},
    {"Trading Card", TRADING_CARD},
    {"Flash Card", FLASH_CARD},
    {"Spare Trousers", SPARE_TROUSERS},
    {"Ramen", RAMEN},
    {"Seltzer", SELTZER},
    {"Castle", CASTLE},
    
    // Rare jokers
    {"DNA", DNA},
    {"Vagabond", VAGABOND},
    {"Baron", BARON},
    {"Obelisk", OBELISK},
    {"Baseball Card", BASEBALL_CARD},
    {"Ancient Joker", ANCIENT_JOKER},
    {"Campfire", CAMPFIRE},
    
    // Legendary jokers
    {"Canio", CANIO},
    {"Triboulet", TRIBOULET},
    {"Yorick", YORICK},
    {"Chicot", CHICOT},
    {"Perkeo", PERKEO},
    
    {"The Mouth", THE_MOUTH},
    {"The Fish", THE_FISH},
    {"The Wall", THE_WALL},
    {"The House", THE_HOUSE},
    {"The Mark", THE_MARK},
    {"The Wheel", THE_WHEEL},
    {"The Arm", THE_ARM},
    {"The Water", THE_WATER},
    {"The Needle", THE_NEEDLE},
    {"The Flint", THE_FLINT},
    {"Standard Tag", STANDARD_TAG},
    {"Meteor Tag", METEOR_TAG},
    {"Buffoon Tag", BUFFOON_TAG},
    {"Handy Tag", HANDY_TAG},
    {"Garbage Tag", GARBAGE_TAG},
    {"Ethereal Tag", ETHEREAL_TAG},
    {"Top-up Tag", TOP_UP_TAG},
    {"Orbital Tag", ORBITAL_TAG},
    {"The Tooth", THE_TOOTH},
    {"The Eye", THE_EYE},
    {"The Plant", THE_PLANT},
    {"The Serpent", THE_SERPENT},
    {"The Ox", THE_OX},
    {"Planet X", PLANET_X},
    {"Ceres", CERES},
    {"Eris", ERIS},
    {"Five of a Kind", FIVE_OF_A_KIND},
    {"Flush House", FLUSH_HOUSE},
    {"Flush Five", FLUSH_FIVE},
    {"Stone Joker", STONE_JOKER},
    {"Steel Joker", STEEL_JOKER},
    {"Lucky Cat", LUCKY_CAT},
    {"Cavendish", CAVENDISH},
    
    // Tarot cards
    {"The Fool", THE_FOOL},
    {"The Magician", THE_MAGICIAN},
    {"The High Priestess", THE_HIGH_PRIESTESS},
    {"The Empress", THE_EMPRESS},
    {"The Emperor", THE_EMPEROR},
    {"The Hierophant", THE_HIEROPHANT},
    {"The Lovers", THE_LOVERS},
    {"The Chariot", THE_CHARIOT},
    {"Justice", JUSTICE},
    {"The Hermit", THE_HERMIT},
    {"The Wheel of Fortune", THE_WHEEL_OF_FORTUNE},
    {"Strength", STRENGTH_CARD},
    {"The Hanged Man", THE_HANGED_MAN},
    {"Death", DEATH},
    {"Temperance", TEMPERANCE},
    {"The Devil", THE_DEVIL},
    {"The Tower", THE_TOWER},
    {"The Star", THE_STAR_CARD},
    {"The Moon", THE_MOON},
    {"The Sun", THE_SUN_CARD},
    {"Judgement", JUDGEMENT},
    {"The World", THE_WORLD},
    
    // Planet cards
    {"Mercury", MERCURY},
    {"Venus", VENUS},
    {"Earth", EARTH},
    {"Mars", MARS},
    {"Jupiter", JUPITER},
    {"Saturn", SATURN},
    {"Uranus", URANUS},
    {"Neptune", NEPTUNE},
    {"Pluto", PLUTO},
    {"Planet X", PLANET_X_CARD},
    {"Ceres", CERES_CARD},
    {"Eris", ERIS_CARD},
    
    // Spectral cards
    {"Familiar", FAMILIAR},
    {"Grim", GRIM},
    {"Incantation", INCANTATION},
    {"Talisman", TALISMAN},
    {"Aura", AURA},
    {"Wraith", WRAITH},
    {"Sigil", SIGIL},
    {"Ouija", OUIJA},
    {"Ectoplasm", ECTOPLASM},
    {"Immolate", IMMOLATE_CARD},
    {"Ankh", ANKH},
    {"Deja Vu", DEJA_VU},
    {"Hex", HEX},
    {"Trance", TRANCE},
    {"Medium", MEDIUM},
    {"Cryptid", CRYPTID},
    
    // Special cards
    {"The Soul", THE_SOUL_CARD},
    {"Black Hole", BLACK_HOLE_CARD}
};

// Use a bitset with enough bits for all items (256 should be plenty)
using LockBitset = std::bitset<256>;

// Fast bitset operations
INLINE_FORCE void lockItem(LockBitset& lockBitmap, ItemID itemId) {
    lockBitmap.set(itemId);
}

INLINE_FORCE void lockItem(LockBitset& lockBitmap, const std::string& itemName) {
    auto it = ITEM_TO_ID.find(itemName);
    if (it != ITEM_TO_ID.end()) {
        lockBitmap.set(it->second);
    } else {
        std::cerr << "ERROR: Trying to lock unknown item: '" << itemName << "'" << std::endl;
        std::cerr << "This item needs to be added to ITEM_TO_ID mapping in bitmap_lock.hpp" << std::endl;
        std::abort();
    }
}

INLINE_FORCE void unlockItem(LockBitset& lockBitmap, ItemID itemId) {
    lockBitmap.reset(itemId);
}

INLINE_FORCE void unlockItem(LockBitset& lockBitmap, const std::string& itemName) {
    auto it = ITEM_TO_ID.find(itemName);
    if (it != ITEM_TO_ID.end()) {
        lockBitmap.reset(it->second);
    } else {
        std::cerr << "ERROR: Trying to unlock unknown item: '" << itemName << "'" << std::endl;
        std::cerr << "This item needs to be added to ITEM_TO_ID mapping in bitmap_lock.hpp" << std::endl;
        std::abort();
    }
}

INLINE_FORCE bool isItemLocked(const LockBitset& lockBitmap, ItemID itemId) {
    return lockBitmap.test(itemId);
}

INLINE_FORCE bool isItemLocked(const LockBitset& lockBitmap, const std::string& itemName) {
    auto it = ITEM_TO_ID.find(itemName);
    if (it != ITEM_TO_ID.end()) {
        return lockBitmap.test(it->second);
    }
    return false; // Item not found, assume not locked
}